title: "Pachecos no Canada"
# email: wowthemesnet@gmail.com
timezone: America/Winnipeg
url: "https://pachecosnocanada.github.io"
baseurl: ""
theme: null
permalink: "/:title/"
logo: '/assets/images/logo_1.png'
favicon: '/assets/images/favicon.ico'
author: Paola Pacheco
paginate: 6
disqus: ''
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed

# Authors
authors:
  paola_pacheco:
    name: Paola Pacheco
    display_name: Paola Pacheco
    avatar: '/assets/images/pachecos.jpg'
    # email: wowthemesnet@gmail.com
    web: https://www.instagram.com/pachecosnocanada
    description: ""

# Social
social:
  instagram: https://www.instagram.com/pachecosnocanada


# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives